const ClipboardEl=document.querySelectorAll(".clipboard-button");const ClipboardEl1=document.querySelector(".clipboard-btn");$(window).scroll(function(){if($(this).scrollTop()>100){$('.backToTop').addClass('active');}else{$('.backToTop').removeClass('active');}});$('.backToTop').click(function(){$("html, body").animate({scrollTop:0},100);return false;});$(".swiper-slide").click(function(){var src=$(this).find("img").attr("src");console.log(src);$(".img-overlay").addClass("active");$(".img-content").html("<img src='"+src+"' class='modal-img' alt='gallery' />");});$(".img-overlay-close").click(function(){$(".img-overlay").removeClass("active");$(".img-content").html("");});let aw1="How can we be sure that the original Uniswap Tosa Inu liquidity creator deleted the wallet key?";$("#planet-1").click(function(){$(".answer").addClass("active");$("body").css("overflow","hidden");$(".shape-content__question").html(aw1);$('.shape-content__answer').text('');$('.shape-content__answer').text(`Immediately after adding liquidity to UniSwap for all 65% of tokens HARUKI locked the pool for 100 years on team.finance platform. 
     He's not joking to make you believe it, see 100 year lock proof on top.
  `);$(".shape-content__action").click(function(){$(".answer").removeClass("active");$("body").css("overflow","auto");});});let aw2="What is your token standard? and where can I safely buy and hold tokens?";$("#planet-2").click(function(){$(".answer").addClass("active");$("body").css("overflow","hidden");$(".shape-content__question").html(aw2);$('.shape-content__answer').text('');$('.shape-content__answer').text(`Tosa Inu is an ERC20 token, you can 
    buy it quickly and securely on Uniswap version V2 and hold the token in all 
    ERC20 standard wallets but preferably Metamask.
    `);$(".shape-content__action").click(function(){$(".answer").removeClass("active");$("body").css("overflow","auto");});});let aw3="Does it cost me to get free Tosa Inu tokens through the wallet check program?";$("#planet-3").click(function(){$(".answer").addClass("active");$("body").css("overflow","hidden");$(".shape-content__question").html(aw3);$('.shape-content__answer').text('');$('.shape-content__answer').text(`
  Oh no you don't lose anything, your job is simply to add a wallet address to receive 
  free tokens and a part of your free tokens has been transferred to our contracted, 
  animal rescue organizations certified.
    `);$(".shape-content__action").click(function(){$(".answer").removeClass("active");$("body").css("overflow","auto");});});let aw4="Can I sell tokens immediately when I receive it from the check wallet program?";$("#planet-4").click(function(){$(".answer").addClass("active");$("body").css("overflow","hidden");$(".shape-content__question").html(aw4);$('.shape-content__answer').text('');$('.shape-content__answer').text(`
  We added liquidity to the token you can sell it instantly, but the community doesn't want to see that, 
  we want you to stay with us.
    `);$(".shape-content__action").click(function(){$(".answer").removeClass("active");$("body").css("overflow","auto");});});let aw5="Will I incur hidden costs and taxes when buying Tosa Inu on trading platforms?";$("#planet-5").click(function(){$(".answer").addClass("active");$("body").css("overflow","hidden");$(".shape-content__question").html(aw5);$('.shape-content__answer').text('');$('.shape-content__answer').text(`
  No you don't lose anything but buying Tosa Inu tokens at the exchange rate, we don't set up any implicit
   tax charges, we don't need it, we need you.
    `);$(".shape-content__action").click(function(){$(".answer").removeClass("active");$("body").css("overflow","auto");});});$(".tab").click(function(){$(".tab").removeClass("active");$(this).addClass("active");$(".tabcontent").removeClass("active");$(".tabcontent").eq($(this).index()).addClass("active");});for(let i=0;i<ClipboardEl.length;i++){ClipboardEl[i].addEventListener("click",function(){const text=ClipboardEl[i].getAttribute("data-clipboard-text");const input=document.createElement("input");input.setAttribute("value",text);document.body.appendChild(input);input.select();const result=document.execCommand("copy");document.body.removeChild(input);if(result){ClipboardEl[i].classList.add("active1");ClipboardEl[i].innerHTML=`<span class="copied mx-auto"><ion-icon style="font-size:28px" name="checkmark-done-outline"></ion-icon></span>`;setTimeout(()=>{ClipboardEl[i].classList.remove("active1");ClipboardEl[i].innerHTML=`<span class="copied "><i class='bx bx-copy fs-5' style='color:#ffffff'></i></span>`;},2000)}},false);}
const ms=window.matchMedia("(max-width: 768px)");ClipboardEl1.addEventListener("click",function(){const text=ClipboardEl1.getAttribute("data-clipboard-text");const input=document.createElement("input");input.setAttribute("value",text);document.body.appendChild(input);input.select();const result=document.execCommand("copy");document.body.removeChild(input);if(result){ClipboardEl1.classList.add("active1");ClipboardEl1.innerHTML=`${ms.matches?`<span class="copied"><ion-icon style="font-size:28px" name="checkmark-done-outline"></ion-icon></span>`:`<span class="copied"><ion-icon  style="font-size:20px" name="checkmark-done-outline"></ion-icon> Copied</span>`}`;setTimeout(()=>{ClipboardEl1.classList.remove("active1");ClipboardEl1.innerHTML=` <i class='bx bx-copy fs-5' style='color:#ffffff'></i> <span class="fs-6 d-none d-md-inline">Donate team</span>`;},2000)}});